# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0003_auto_20150720_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterfield',
            name='filter_type',
            field=models.CharField(blank=True, choices=[('exact', 'Equals'), ('iexact', 'Equals (case-insensitive)'), ('contains', 'Contains'), ('icontains', 'Contains (case-insensitive)'), ('in', 'in (comma seperated 1,2,3)'), ('gt', 'Greater than'), ('gte', 'Greater than equals'), ('lt', 'Less than'), ('lte', 'Less than equals'), ('startswith', 'Starts with'), ('istartswith', 'Starts with (case-insensitive)'), ('endswith', 'Ends with'), ('iendswith', 'Ends with  (case-insensitive)'), ('range', 'range'), ('week_day', 'Week day'), ('isnull', 'Is null'), ('regex', 'Regular Expression'), ('iregex', 'Reg. Exp. (case-insensitive)'), ('max', 'Max (annotation-filter)'), ('min', 'Min (annotation-filter)')], default='icontains', max_length=20),
        ),
    ]
