# Generated by Django 2.0.4 on 2018-04-13 07:47

from django.db import migrations, models
import django.db.models.deletion
import report_builder.models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0005_add_delta_filtering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='root_model',
            field=models.ForeignKey(limit_choices_to=report_builder.models.get_limit_choices_to_callable, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
