# Generated by Django 2.1 on 2019-02-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0006_auto_20180413_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterfield',
            name='filter_value',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
