# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_models', '0011_auto_20180413_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='foos',
            field=models.ManyToManyField(blank=True, related_name='bar_set', to='demo_models.Foo'),
        ),
    ]
