# Generated by Django 2.0.4 on 2018-04-13 07:47

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder_scheduled', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='last_run_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Staff users to notify', limit_choices_to={'is_staff': True}, to=settings.AUTH_USER_MODEL),
        ),
    ]
